# Macos Build

name: macos-build-hrdb

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install libs
        run: |
           brew install qt5
           brew install sdl2
           echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
           echo "Qt5_DIR=/usr/local/opt/qt@5/lib/cmake/Qt5" >> $GITHUB_ENV
           mkdir output
           curl -O https://www.libsdl.org/release/SDL2-2.0.18.dmg
           hdiutil attach SDL2-2.0.18.dmg
           ls -Rl /Volumes/SDL2/
      - name: Build hatari
        run: |
          ./configure
          make -j 2
          cd src
          ls -Rl
          chmod +x hatari.app/Contents/MacOS/hatari
          mkdir hatari.app/Contents/Frameworks
          cp -R /Volumes/SDL2/SDL2.framework hatari.app/Contents/Frameworks
          mv hatari.app ../output/
      - name: build hrdb
        run: |
          export
          cd tools/hrdb
          qmake .
          make
          chmod +x hrdb.app/Contents/MacOS/hrdb
      - name: package
        run: |
           cd tools/hrdb
           macdeployqt hrdb.app
           ls -Rl *
           mv hrdb.app ../../output/
      - name: zip outputs
        run: |
          cd output
          cp ../tools/hrdb/docs/hrdb_release_notes.txt .
          cp ../gpl.txt .
          zip -r macos-hrdb.zip hrdb.app hatari.app *.txt      
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: hrdb-${{ github.sha }}
          path: output/macos-hrdb.zip
          
          
           
