# Super ripped from https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
# and some from https://github.com/ilammy/msvc-dev-cmd/blob/master/.github/workflows/release.yml
#
name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
         #{ msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    steps:

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-x86_64-toolchain #mingw-w64-i686-toolchain 
          #update: true
          release: false

      - uses: actions/checkout@v2

      - name: "Copy qt dll files"
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S make mingw-w64-x86_64-qt5 mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-portmidi #mingw32/mingw-w64-i686-attica-qt5 mingw-w64-i686-SDL2 mingw32/mingw-w64-i686-portmidi 
          #mkdir hrdb
          mkdir hrdb64
          #cd hrdb
          #cd ../hrdb64
          #cd ..
          #mkdir -p fastbuild/cpu
          #mkdir -p fastbuild/debug
          #mkdir -p fastbuild/falcon
          #mkdir -p fastbuild/floppy
          #mkdir -p fastbuild/guisdl
          #mkdir -p fastbuild/hatari
          #mkdir -p fastbuild/uaecpu
          #chmod 777 -R fastbuild
          #chmod 777 fastbuild
          chmod 777 -R fastbuild_x64
          chmod 777 fastbuild_x64

      - name: "Build hatari"
        shell: cmd
        run: |
          #cd fastbuild
          #fbuild -showcmds
          #move hrdb.exe ..\hrdb
          cd fastbuild_x64
          fbuild -showcmds
          move hrdb.exe ..\hrdb64
          move hatari.exe ..\hrdb64

      - name: "Post qt build steps"
        shell: msys2 {0}
        run: |
          #cd hrdb
          #for i in `ldd hrdb.exe | awk '{print $3}'`; do cp $i .;done
          #for i in `ldd hatari.exe | awk '{print $3}'`; do cp $i .;done
          #for i in `for j in $(ls *.dll); do ldd $j;done|grep -vi System32|awk '{print $1}'|sort -u`; do cp /mingw32/bin/$i .;done
          #for i in `for j in $(ls *.dll); do ldd $j;done|grep -vi System32|awk '{print $1}'|sort -u`; do cp /mingw32/bin/$i .;done
          #for i in `for j in $(ls *.dll); do ldd $j;done|grep -vi System32|awk '{print $1}'|sort -u`; do cp /mingw32/bin/$i .;done
          #for i in `for j in $(ls *.dll); do ldd $j;done|grep -vi System32|awk '{print $1}'|sort -u`; do cp /mingw32/bin/$i .;done
          #for i in `for j in $(ls *.dll); do ldd $j;done|grep -vi System32|awk '{print $1}'|sort -u`; do cp /mingw32/bin/$i .;done
          #for i in `for j in $(ls *.dll); do ldd $j;done|grep -vi System32|awk '{print $1}'|sort -u`; do cp /mingw32/bin/$i .;done
          # -no-translations is a workaround for some versions of windeployqt barfing due to a regression. See https://forum.qt.io/topic/124947/error-running-windeployqt/9 and hope that tat doesn't add translations soon?
          #windeployqt . -no-translations
          #mv ../fastbuild/hatari.exe .
          set -x
          cd hrdb64
          for i in `ldd hrdb.exe | awk '{print $3}'|grep -vi not`; do echo $i; cp $i .;done
          for i in `ldd hatari.exe | awk '{print $3}'|grep -vi not`; do echo $i; cp $i .;done
          for i in `for j in $(ls *.dll); do ldd $j;done|awk '{print $3}'|sort -u|grep -vi not|grep -vi $PWD`; do echo $i; cp $i .;done
          for i in `for j in $(ls *.dll); do ldd $j;done|awk '{print $3}'|sort -u|grep -vi not|grep -vi $PWD`; do echo $i; cp $i .;done
          for i in `for j in $(ls *.dll); do ldd $j;done|awk '{print $3}'|sort -u|grep -vi not|grep -vi $PWD`; do echo $i; cp $i .;done
          for i in `for j in $(ls *.dll); do ldd $j;done|awk '{print $3}'|sort -u|grep -vi not|grep -vi $PWD`; do echo $i; cp $i .;done
          for i in `for j in $(ls *.dll); do ldd $j;done|awk '{print $3}'|sort -u|grep -vi not|grep -vi $PWD`; do echo $i; cp $i .;done
          for i in `for j in $(ls *.dll); do ldd $j;done|awk '{print $3}'|sort -u|grep -vi not|grep -vi $PWD`; do echo $i; cp $i .;done
          export PATH=/mingw64/bin:$PATH
          /C/msys64/mingw64/bin/windeployqt.exe hrdb.exe -no-translations
          
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: hatari-debugger-${{ github.sha }}
          path: |
              #hrdb/
              hrdb64/
