# Super ripped from https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
# and some from https://github.com/ilammy/msvc-dev-cmd/blob/master/.github/workflows/release.yml
#
name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
         #{ msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    steps:

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain
          #update: true
          release: false

      - uses: actions/checkout@v2

      - name: "Copy qt dll files"
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S make mingw32/mingw-w64-i686-attica-qt5 mingw-w64-i686-SDL2
          #cd tools/hrdb
          #qmake
          #make
          #windeployqt release/
          #rm *.cpp
          #rm *.o
          #cd ..
          #mv release hrdb
          #mv hrdb ../..
          # This is for the hatari build, but echo in cmd.exe does weird stuff with >
          # Not needed anymore
          #echo '#include <string.h>' > /C/msys64//usr/include/memory.h
          mkdir hrdb
          cd hrdb
          cp /C/msys64/mingw32/bin/libgcc_s_dw2-1.dll .
          cp /C/msys64/mingw32/bin/libstdc++-6.dll .
          cp /C/msys64/mingw32/bin/libbrotlicommon.dll .
          cp /C/msys64/mingw32/bin/libbrotlidec.dll .
          cp /C/msys64/mingw32/bin/libharfbuzz-0.dll .
          cp /C/msys64/mingw32/bin/libglib-2.0-0.dll .
          cp /C/msys64/mingw32/bin/libfreetype-6.dll .
          cp /C/msys64/mingw32/bin/libiconv-2.dll .
          cp /C/msys64/mingw32/bin/libintl-8.dll .
          cp /C/msys64/mingw32/bin/libwinpthread-1.dll .
          cp /C/msys64/mingw32/bin/libgraphite2.dll .
          cp /C/msys64/mingw32/bin/libzstd.dll .
          cp /C/msys64/mingw32/bin/libpcre2-16-0.dll .
          cp /C/msys64/mingw32/bin/libicudt*.dll .
          cp /C/msys64/mingw32/bin/libicuin*.dll .
          cp /C/msys64/mingw32/bin/libicuuc*.dll .
          cp /C/msys64/mingw32/bin/libpcre-1.dll .
          cp /C/msys64/mingw32/bin/libbz2-1.dll .
          cp /C/msys64/mingw32/bin/libdouble-conversion.dll .
          cp /C/msys64/mingw32/bin/zlib1.dll .
          cp /C/msys64/mingw32/bin/libpng16-16.dll .
          cp /C/msys64/mingw32/bin/SDL2.dll .
          # Remove unneeded dlls
          rm libicuucd*.dll
          rm libicudtd*.dll

      - name: "Build hatari"
        shell: cmd
        run: |
          cd fastbuild
          fbuild
          move hrdb.exe ..\hrdb

      - name: "Post qt build steps"
        shell: msys2 {0}
        run: |
          cd hrdb
          windeployqt .
          mv ../fastbuild/hatari.exe .
          
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: hatari-debugger-${{ github.sha }}
          path: |
              hrdb/
